#pragma once
#include "evolution-parameters.h"
#include "../mars-interface/interface.h"

/// <summary>
/// Changes the length of the warrior
/// </summary>
/// <param name="warrior">A warrior to modify</param>
/// <param name="params">Evolution parameters</param>
warrior_s* mutate_length(warrior_s* warrior, evolution_params* params);

/// <summary>
/// Return a warrior resulting from the mutation of the instructions of the past warrior's code according to a probability passed into parameter 
/// </summary>
/// <param name="warrior">A warrior to modify</param>
/// <param name="mutate_proba">Probability of mutations</param>
/// <param name="params">Evolution parameters</param>
/// <returns>Return a New Mutated Warrior</returns>
warrior_s* mutate(warrior_s* warrior, evolution_params* params);


/// <summary>
/// Return a warrior resulting from the fusion of warrior1's code with warrior2's code according to a probability passed into parameter 
/// </summary>
/// <param name="warrior1">The first warrior</param>
/// <param name="warrior2">The second warrior</param>
/// <param name="params">Evolution parameters</param>
/// <returns>Returns the fusion of the two warriors</returns>
warrior_s* breed(warrior_s* warrior1, warrior_s* warrior2, evolution_params* params);

/// <summary>
/// Return warriors generated by the evolution algorithm according to the parameters shown
/// </summary>
/// <param name="warriors">A list of warriors</param>
/// <param name="params">Evolution parameters</param>
/// <returns>The warriors generated by the evolution algorithm</returns>
warrior_s** evolution_algorithmV1(warrior_s** warriors, evolution_params* params);

void print_results(char* json_file, float score);