#pragma once
#include "../mars-interface/interface.h"
#include "../../lib/cJSON/cJSON.h"

struct generator
{
	void* stats;
	int depth;
};
#define generator struct generator

void free_stats(void* stats, int depth);

void free_generator(generator* gen);

void decode_json(void* stats, cJSON* json, int depth);

/// <summary>
/// Recover the statistics generated by Redcode Stats and return them to a float table
/// </summary>
/// <param name="path">Path to statistics</param>
/// <returns>A structure containing statistics about warrior, to be used as a generator</returns>
generator* decode_stats(char* path, int depth);

/// <summary>
/// Initialize a warrior's code from the statistics generated by Redcode Stats
/// </summary>
/// <param name="gen">Warrior generator</param>
/// <returns>A warrior generated by Redcode Stats</returns>
warrior_s* make_warrior(generator* gen);