#pragma once
#include "../mars-interface/interface.h"
#include "../../lib/cJSON/cJSON.h"

/// <summary>
/// This structure contains a statistic table and the dimension of its depth.
/// </summary>
typedef struct generator
{
	void* stats;
	int depth;
} generator;

#include "../../lib/cJSON/cJSON.h"
#include "../mars-interface/interface.h"
#include "../evolution-algorithm/evolution-parameters.h"

/// <summary>
/// Releases the memory taken up by a statistics table.
/// </summary>
/// <param name="stats">An array of pointers whose dimension is depth and which contains floats.</param>
/// <param name="depth">The depth of the statistics table.</param>
void free_stats(void* stats, int depth);

/// <summary>
/// Free the memory taken by a generator structure.
/// </summary>
/// <param name="gen">A generator structure</param>
void free_generator(generator* gen);

/// <summary>
/// Decodes the content of a cJSON variable and puts the resulting values in an array 
/// of statistics of dimension depth.
/// </summary>
/// <param name="stats">An array of pointers whose dimension is depth and which contains floats.</param>
/// <param name="json">A cJSON pointer containing statistics to decode.</param>
/// <param name="depth">The depth of the statistics table.</param>
void decode_json(void* stats, cJSON* json, int depth);

/// <summary>
/// Recover the statistics generated by Redcode Stats and return them to a generator structure.
/// </summary>
/// <param name="path">Path to statistics</param>
/// <param name="depth">The depth of the new statistics table.</param>
/// <returns>A generator structure</returns>
generator* decode_stats(char* path, int depth);

/// <summary>
/// Initialize a warrior's code from the statistics generated by Redcode Stats found in evolution_params
/// </summary>
/// <param name="params">Evolution parameters</param>
/// <returns>A warrior generated by Redcode Stats</returns>
warrior_s* make_warrior(evolution_params* params);